# -*- coding: utf-8 -*-
"""streamlit_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zxgZnYB836kapddI8ov_0ekeJUabov37
"""

import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from datetime import datetime

# --- PAGE CONFIGURATION ---
st.set_page_config(
    page_title="Travel Ticket Analysis",
    page_icon="✈️",
    layout="wide",
    initial_sidebar_state="expanded",
)

# --- DATA LOADING ---
@st.cache_data
def load_data():
    """Loads the travel tickets dataset."""
    df = pd.read_csv("EDA_cleaned.csv")

    # Convert date columns to datetime
    df['Created'] = pd.to_datetime(df['Created'])
    df['DepartureTime'] = pd.to_datetime(df['DepartureTime'])

    # Calculate days until departure
    df['DaysUntilDeparture'] = (df['DepartureTime'] - df['Created']).dt.days

    # Create price categories
    df['PriceCategory'] = pd.cut(df['Price'],
                               bins=[0, 1000000, 5000000, 10000000, float('inf')],
                               labels=['<1M', '1M-5M', '5M-10M', '>10M'])

    return df

df = load_data()

# --- APP TITLE AND DESCRIPTION ---
st.title("✈️ Travel Tickets Data Analysis")
st.markdown("""
This application performs exploratory data analysis (EDA) on the Travel Tickets dataset.
Use the filters in the sidebar to explore different aspects of ticket sales and customer behavior.
""")

# --- SIDEBAR FOR FILTERS ---
st.sidebar.header("Filter Your Data")

# Filter for vehicle type
vehicle_types = st.sidebar.multiselect(
    "Select Vehicle Type",
    options=df["Vehicle"].unique(),
    default=df["Vehicle"].unique()
)

# Filter for trip reason
trip_reasons = st.sidebar.multiselect(
    "Select Trip Reason",
    options=df["TripReason"].unique(),
    default=df["TripReason"].unique()
)

# Filter for domestic/international
domestic_filter = st.sidebar.multiselect(
    "Select Trip Type",
    options=df["Domestic"].unique(),
    default=df["Domestic"].unique()
)

# Filter for cancellation status
cancel_filter = st.sidebar.multiselect(
    "Select Cancel Status",
    options=df["Cancel"].unique(),
    default=df["Cancel"].unique()
)

# Filter for price range
min_price, max_price = int(df["Price"].min()), int(df["Price"].max())
price_range = st.sidebar.slider(
    "Select Price Range",
    min_value=min_price,
    max_value=max_price,
    value=(min_price, max_price),
)

# Filter for gender
gender_filter = st.sidebar.multiselect(
    "Select Gender",
    options=["Male" if x == 1 else "Female" for x in df["Male"].unique()],
    default=["Male" if x == 1 else "Female" for x in df["Male"].unique()]
)

# --- FILTERING THE DATAFRAME ---
df_selection = df.copy()

# Apply filters
if vehicle_types:
    df_selection = df_selection[df_selection["Vehicle"].isin(vehicle_types)]
if trip_reasons:
    df_selection = df_selection[df_selection["TripReason"].isin(trip_reasons)]
if domestic_filter:
    df_selection = df_selection[df_selection["Domestic"].isin(domestic_filter)]
if cancel_filter:
    df_selection = df_selection[df_selection["Cancel"].isin(cancel_filter)]
if gender_filter:
    gender_numeric = [1 if x == "Male" else 0 for x in gender_filter]
    df_selection = df_selection[df_selection["Male"].isin(gender_numeric)]

# Apply price filter
df_selection = df_selection[
    (df_selection["Price"] >= price_range[0]) &
    (df_selection["Price"] <= price_range[1])
]

# Display error message if no data is selected
if df_selection.empty:
    st.warning("No data available for the selected filters. Please adjust your selection.")
    st.stop()

# --- MAIN PAGE CONTENT ---
st.subheader("📊 Key Metrics")

# --- DISPLAY KEY METRICS ---
col1, col2, col3, col4 = st.columns(4)

with col1:
    total_tickets = df_selection.shape[0]
    st.metric(label="Total Tickets", value=f"{total_tickets:,}")

with col2:
    avg_price = round(df_selection["Price"].mean(), 2)
    st.metric(label="Average Price", value=f"${avg_price:,.2f}")

with col3:
    cancellation_rate = (df_selection["Cancel"].sum() / len(df_selection)) * 100
    st.metric(label="Cancellation Rate", value=f"{cancellation_rate:.1f}%")

with col4:
    avg_discount = round(df_selection["CouponDiscount"].mean(), 2)
    st.metric(label="Average Discount", value=f"${avg_discount:,.2f}")

st.markdown("---")

# --- VISUALIZATIONS ---
st.subheader("📈 Visualizations")

# Arrange charts in columns
viz_col1, viz_col2 = st.columns(2)

with viz_col1:
    # Price distribution by vehicle type
    st.subheader("Price Distribution by Vehicle Type")
    fig1 = px.box(df_selection, x="Vehicle", y="Price", color="Vehicle")
    fig1.update_layout(height=400)
    st.plotly_chart(fig1, use_container_width=True)

with viz_col2:
    # Ticket count by vehicle type
    st.subheader("Ticket Count by Vehicle Type")
    vehicle_counts = df_selection["Vehicle"].value_counts()
    fig2 = px.pie(values=vehicle_counts.values, names=vehicle_counts.index)
    fig2.update_layout(height=400)
    st.plotly_chart(fig2, use_container_width=True)

# Second row of visualizations
viz_col3, viz_col4 = st.columns(2)

with viz_col3:
    # Average price by trip reason
    st.subheader("Average Price by Trip Reason")
    avg_price_reason = df_selection.groupby("TripReason")["Price"].mean().reset_index()
    fig3 = px.bar(avg_price_reason, x="TripReason", y="Price", color="TripReason")
    fig3.update_layout(height=400)
    st.plotly_chart(fig3, use_container_width=True)

with viz_col4:
    # Cancellation rate by vehicle type
    st.subheader("Cancellation Rate by Vehicle Type")
    cancel_by_vehicle = df_selection.groupby("Vehicle")["Cancel"].mean() * 100
    fig4 = px.bar(x=cancel_by_vehicle.index, y=cancel_by_vehicle.values)
    fig4.update_layout(xaxis_title="Vehicle", yaxis_title="Cancellation Rate (%)", height=400)
    st.plotly_chart(fig4, use_container_width=True)

# Third row - Time series analysis
st.subheader("📅 Time Series Analysis")
time_col1, time_col2 = st.columns(2)

with time_col1:
    # Tickets by creation month
    st.subheader("Tickets by Creation Month")
    df_selection['CreatedMonth'] = df_selection['Created'].dt.to_period('M').astype(str)
    monthly_tickets = df_selection.groupby('CreatedMonth').size().reset_index(name='Count')
    fig5 = px.line(monthly_tickets, x='CreatedMonth', y='Count')
    fig5.update_layout(height=400)
    st.plotly_chart(fig5, use_container_width=True)

with time_col2:
    # Average days until departure by vehicle type
    st.subheader("Average Days Until Departure")
    avg_days = df_selection.groupby("Vehicle")["DaysUntilDeparture"].mean().reset_index()
    fig6 = px.bar(avg_days, x="Vehicle", y="DaysUntilDeparture", color="Vehicle")
    fig6.update_layout(height=400)
    st.plotly_chart(fig6, use_container_width=True)

# --- DISPLAY RAW DATA ---
with st.expander("View Raw Data"):
    st.dataframe(df_selection)
    st.markdown(f"**Data Dimensions:** {df_selection.shape[0]} rows, {df_selection.shape[1]} columns")

st.markdown("---")
st.write("Data Source: Travel Tickets Dataset")