# -*- coding: utf-8 -*-
"""streamlit_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zxgZnYB836kapddI8ov_0ekeJUabov37
"""

import streamlit as st
import pandas as pd

# --- PAGE CONFIGURATION ---
st.set_page_config(
    page_title="Customer Churn Analysis",
    page_icon="📊",
    layout="wide",
    initial_sidebar_state="expanded",
)

# --- DATA LOADING ---
@st.cache_data
def load_data():
    """Loads the customer churn dataset."""
    df = pd.read_csv("Data/EDA_cleaned.csv")
    return df

df = load_data()

# --- APP TITLE AND DESCRIPTION ---
st.title("📊 Customer Churn Analysis Dashboard")
st.markdown("""
This application performs exploratory data analysis (EDA) on the Customer Churn dataset.
Use the filters in the sidebar to explore customer behavior and churn patterns.
""")

# --- SIDEBAR FOR FILTERS ---
st.sidebar.header("Filter Customers")

# Filter for Churn status
churn_status = st.sidebar.multiselect(
    "Select Churn Status",
    options=df["Churn"].unique(),
    default=df["Churn"].unique()
)

# Filter for City Tier
city_tier = st.sidebar.multiselect(
    "Select City Tier",
    options=df["CityTier"].unique(),
    default=df["CityTier"].unique()
)

# Filter for Gender
gender = st.sidebar.multiselect(
    "Select Gender",
    options=df["Gender"].unique(),
    default=df["Gender"].unique()
)

# Filter for Preferred Login Device
login_device = st.sidebar.multiselect(
    "Select Preferred Login Device",
    options=df["PreferredLoginDevice"].unique(),
    default=df["PreferredLoginDevice"].unique()
)

# Filter for Preferred Payment Mode
payment_mode = st.sidebar.multiselect(
    "Select Preferred Payment Mode",
    options=df["PreferredPaymentMode"].unique(),
    default=df["PreferredPaymentMode"].unique()
)

# Filter for Preferred Order Category
order_cat = st.sidebar.multiselect(
    "Select Preferred Order Category",
    options=df["PreferedOrderCat"].unique(),
    default=df["PreferedOrderCat"].unique()
)

# Filter for Tenure range
min_tenure, max_tenure = int(df["Tenure"].min()), int(df["Tenure"].max())
tenure_slider = st.sidebar.slider(
    "Select Tenure Range",
    min_value=min_tenure,
    max_value=max_tenure,
    value=(min_tenure, max_tenure),
)

# Filter for Satisfaction Score
satisfaction = st.sidebar.multiselect(
    "Select Satisfaction Score",
    options=df["SatisfactionScore"].unique(),
    default=df["SatisfactionScore"].unique()
)

# --- FILTERING THE DATAFRAME ---
df_selection = df.copy()

# Apply multiselect filters only if a selection has been made for that filter
if churn_status:
    df_selection = df_selection[df_selection["Churn"].isin(churn_status)]
if city_tier:
    df_selection = df_selection[df_selection["CityTier"].isin(city_tier)]
if gender:
    df_selection = df_selection[df_selection["Gender"].isin(gender)]
if login_device:
    df_selection = df_selection[df_selection["PreferredLoginDevice"].isin(login_device)]
if payment_mode:
    df_selection = df_selection[df_selection["PreferredPaymentMode"].isin(payment_mode)]
if order_cat:
    df_selection = df_selection[df_selection["PreferedOrderCat"].isin(order_cat)]
if satisfaction:
    df_selection = df_selection[df_selection["SatisfactionScore"].isin(satisfaction)]

# Apply slider filter
df_selection = df_selection[
    (df_selection["Tenure"] >= tenure_slider[0]) &
    (df_selection["Tenure"] <= tenure_slider[1])
]

# Display error message if no data is selected
if df_selection.empty:
    st.warning("No data available for the selected filters. Please adjust your selection.")
    st.stop()

# --- MAIN PAGE CONTENT ---
st.subheader("📈 Key Metrics")

# --- DISPLAY KEY METRICS ---
col1, col2, col3, col4 = st.columns(4)

with col1:
    total_customers = df_selection.shape[0]
    st.metric(label="Total Customers", value=total_customers)

with col2:
    churn_rate = (df_selection["Churn"].sum() / total_customers) * 100
    st.metric(label="Churn Rate", value=f"{churn_rate:.1f}%")

with col3:
    avg_tenure = round(df_selection["Tenure"].mean(), 1)
    st.metric(label="Average Tenure", value=avg_tenure)

with col4:
    avg_cashback = round(df_selection["CashbackAmount"].mean(), 1)
    st.metric(label="Avg. Cashback Amount", value=f"${avg_cashback:.2f}")

# Additional metrics
col5, col6, col7, col8 = st.columns(4)

with col5:
    avg_order_count = round(df_selection["OrderCount"].mean(), 1)
    st.metric(label="Avg. Order Count", value=avg_order_count)

with col6:
    avg_coupon_used = round(df_selection["CouponUsed"].mean(), 1)
    st.metric(label="Avg. Coupon Used", value=avg_coupon_used)

with col7:
    complain_rate = (df_selection["Complain"].sum() / total_customers) * 100
    st.metric(label="Complain Rate", value=f"{complain_rate:.1f}%")

with col8:
    avg_hours_app = round(df_selection["HourSpendOnApp"].mean(), 1)
    st.metric(label="Avg. Hours on App", value=avg_hours_app)

st.markdown("---")

# --- VISUALIZATIONS ---
st.subheader("📊 Visualizations")

# Arrange charts in columns
viz_col1, viz_col2 = st.columns(2)

with viz_col1:
    # Churn distribution - using bar chart instead of pie
    st.subheader("Churn Distribution")
    churn_counts = df_selection["Churn"].value_counts()
    # Convert to DataFrame for bar chart
    churn_df = pd.DataFrame({
        'Churn Status': ['Not Churned', 'Churned'],
        'Count': churn_counts.values
    })
    st.bar_chart(churn_df.set_index('Churn Status'))

with viz_col2:
    # Average Cashback by Churn Status
    st.subheader("Avg. Cashback by Churn Status")
    avg_cashback_by_churn = df_selection.groupby('Churn')['CashbackAmount'].mean()
    st.bar_chart(avg_cashback_by_churn)

# Second row of visualizations
viz_col3, viz_col4 = st.columns(2)

with viz_col3:
    # Satisfaction Score Distribution
    st.subheader("Satisfaction Score Distribution")
    satisfaction_counts = df_selection["SatisfactionScore"].value_counts().sort_index()
    st.bar_chart(satisfaction_counts)

with viz_col4:
    # Tenure Distribution
    st.subheader("Tenure Distribution")
    tenure_hist = df_selection["Tenure"].value_counts().sort_index()
    st.line_chart(tenure_hist)

# Third row of visualizations
viz_col5, viz_col6 = st.columns(2)

with viz_col5:
    # Preferred Payment Mode
    st.subheader("Preferred Payment Mode")
    payment_counts = df_selection["PreferredPaymentMode"].value_counts()
    st.bar_chart(payment_counts)

with viz_col6:
    # City Tier Distribution
    st.subheader("City Tier Distribution")
    city_counts = df_selection["CityTier"].value_counts().sort_index()
    st.bar_chart(city_counts)

# Fourth row of visualizations
viz_col7, viz_col8 = st.columns(2)

with viz_col7:
    # Preferred Order Category
    st.subheader("Preferred Order Category")
    order_cat_counts = df_selection["PreferedOrderCat"].value_counts()
    st.bar_chart(order_cat_counts)

with viz_col8:
    # Gender Distribution
    st.subheader("Gender Distribution")
    gender_counts = df_selection["Gender"].value_counts()
    st.bar_chart(gender_counts)

# Scatter plot for numerical relationship
st.subheader("Tenure vs Cashback Amount")
scatter_data = df_selection[['Tenure', 'CashbackAmount', 'Churn']]
scatter_data['Churn'] = scatter_data['Churn'].map({0: 'Not Churned', 1: 'Churned'})
st.scatter_chart(
    data=scatter_data,
    x='Tenure',
    y='CashbackAmount',
    color='Churn'
)

# Additional scatter plot
st.subheader("Order Count vs Cashback Amount")
scatter_data2 = df_selection[['OrderCount', 'CashbackAmount', 'Churn']]
scatter_data2['Churn'] = scatter_data2['Churn'].map({0: 'Not Churned', 1: 'Churned'})
st.scatter_chart(
    data=scatter_data2,
    x='OrderCount',
    y='CashbackAmount',
    color='Churn'
)

# --- DATA SUMMARY ---
st.subheader("📋 Data Summary")

# Display some statistics
col9, col10, col11 = st.columns(3)

with col9:
    st.write("**Churn Statistics:**")
    st.write(f"- Churned Customers: {df_selection['Churn'].sum()}")
    st.write(f"- Non-Churned Customers: {len(df_selection) - df_selection['Churn'].sum()}")
    st.write(f"- Churn Rate: {churn_rate:.2f}%")

with col10:
    st.write("**Order Statistics:**")
    st.write(f"- Avg Orders per Customer: {avg_order_count}")
    st.write(f"- Avg Coupons Used: {avg_coupon_used}")
    st.write(f"- Customers with Complaints: {df_selection['Complain'].sum()}")

with col11:
    st.write("**Engagement Statistics:**")
    st.write(f"- Avg Hours on App: {avg_hours_app}")
    st.write(f"- Avg Devices Registered: {df_selection['NumberOfDeviceRegistered'].mean():.1f}")
    st.write(f"- Avg Addresses: {df_selection['NumberOfAddress'].mean():.1f}")

# --- DISPLAY RAW DATA ---
with st.expander("View Filtered Data"):
    st.dataframe(df_selection)
    st.markdown(f"**Data Dimensions:** {df_selection.shape[0]} rows, {df_selection.shape[1]} columns")

st.markdown("---")
st.write("Customer Churn Analysis Dashboard - EDA Tool")